id = com.zen.Calculator
name = Calculator
version = 1.0
executable = Calculator
icon = calculator
category = utilities
copyright = Copyright © 2026 Zen OS contributors
description = Basic and scientific calculator
