id = com.zen.ActivityMonitor
name = Activity Monitor
version = 1.0
executable = ActivityMonitor
icon = activity
category = utilities
copyright = Copyright © 2026 Zen OS contributors
description = Processes, CPU and memory
