com.zen.security.app-sandbox
com.zen.security.files.user-selected.read-only
com.zen.security.files.pictures.read-write
com.zen.security.files.downloads.read-write
com.zen.security.files.documents.read-only
