id = com.zen.Terminal
name = Terminal
version = 1.0
executable = Terminal
icon = terminal
category = utilities
copyright = Copyright © 2026 Zen OS contributors
description = Command-line access to Zen OS
