id = com.zen.TextEdit
name = TextEdit
version = 1.0
executable = TextEdit
icon = textedit
category = productivity
copyright = Copyright © 2026 Zen OS contributors
description = Write and edit plain text documents
