# Services supervised by init.
# name          restart  path [args...]
ptyd            always   /System/Library/Servers/ptyd
launchd         always   /System/Library/Servers/launchd
windowserver    always   /System/Library/Servers/windowserver
loginwindow     always   /System/Library/CoreServices/loginwindow
getty           always   /usr/sbin/getty debug:
